services:
  # Serviço da aplicação NestJS
  app:
    build:
      context: . # Usa o Dockerfile na pasta atual
      dockerfile: Dockerfile
    container_name: meu-app-nest
    env_file:
      - .env # Carrega as variáveis do arquivo .env
    ports:
      - "${APP_PORT}:${APP_PORT}" # Usa a variável do .env para mapear a porta
    volumes:
      - .:/usr/src/app # Espelha todo o projeto para dentro do contêiner
      - /usr/src/app/node_modules # "Trava" a pasta node_modules de dentro do contêiner
    # Comando para rodar em modo de desenvolvimento com hot-reloading
    command: npm run start:dev
    depends_on:
      - db

  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: user-db
    env_file:
      - .env # Também carrega as variáveis do .env
    environment:
      # Mapeia as variáveis do .env para as que o container do Postgres espera
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: